# Language: uzbek / english
language: english

# Broadcast interval in seconds
interval: 300

# Messages to broadcast
messages:
  - "&aWelcome to the Farmon server!"
  - "&bWe have daily updates!"
  - "&eInvite your friends to join!"
