name: Farmon
version: 1.0
main: uz.pyksel.farmon.Farmon
api-version: 1.13
author: Pyksel
description: A plugin that manages the command system on the server
commands:
  farmon:
    description: Reload command
    usage: /farmon reload
    permission: farmon.reload
